version: '3'
services:
  serviceb:
    image: 205375198116.dkr.ecr.us-east-1.amazonaws.com/serviceb:latest
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: tutorial
        awslogs-region: us-east-1
        awslogs-stream-prefix: serviceb
